# FILE For excel



START_DAY_UPDATE = "2022-08-06"
END_DAY_UPDATE = '2022-11-06'

QUARTER_KEY = "3/2022"
YEAR_KEY = "2021"
TYPE_TIME = False # QUATER
# TYPE_TIME = True # YEAR


# merge

QUARTER_FINANCAIL_FIX_FILE = "Financial_Quarter"
QUARTER_FINANCAIL_FIX_FILE_BY_HUMAN = "DataFix"

# Storage
PATH_DISTILLATION_VIETNAM_ALLREAL = "G:\My Drive\DataVIS\VietNam\Data Lake\Distillation\All_Real"
PATH_DISTILLATION_VIETNAM_ADDITIONALDATA = "G:\My Drive\DataVIS\VietNam\Data Lake\Distillation\Additional_Data"

COMPANY_ACTIVE = ['REE','SAM','TMS','VNM','FPT','GMD','GIL','HAS','SAV','DHA']
COMPANY_DELETE = ['KTS','SGD','SLS','VE1','HLY','MPC','VVN','TCH','IPA','PVI','TVC','EFI','HSA','MCD','PVR']